### ISSUE TITLE
工业控制页面细节调整

### ISSUE THREAD

**Issue by zhuozihan** [zsxt/inspire#16]
- [ ] 导航栏改为“工业控制”
- [ ] 全球态势的title放在顶部、中央，地图和title中间的空白留大一些，图的高度可适当调高
- [ ] 全国态势与上条一样修改，把左上角无关的“全国搜索结果”数据去掉

**Comment by iEverX** [comment]
@monkback 所有页面的内容都放到warpper wrapper-content中，可以参考icpAnalysis.html中的写法。result和monitor交给 @pdliu

**Comment by monkback** [comment]
done
