### ISSUE TITLE
工业控制页面 

### ISSUE THREAD

**Issue by iEverX** [zsxt/inspire#17]
- [x] 结果统计tab，把两个图放到ibox中
- [x] 监控预警tab，标题放到图的上方。同时把图放到ibox中

所有页面的的内容放到wrapper wrapper-content中，参考icpAnalysis.html中的写法

**Comment by iEverX** [comment]
4月8日（下周五）之前完成

**Comment by pdliu** [comment]
我提交了，champion2478是这个台式机上别人的旧帐号。

**Comment by pdliu** [comment]
我就挪了3个标题的位置，其余“放到ibox中，放到wrapper wrapper-content中”在monkback提交的代码中已修改。
