### ISSUE TITLE
工控安全页面

### ISSUE THREAD

**Issue by iEverX** [zsxt/inspire#2]
- [ ] 标题等全部改为中文
- [ ] 左侧导航栏的子级目录形式，是不是比较好？
- [ ] 导航栏图标与主动扫描一致了，修改为其他
- [ ] Result子页面的2个图表大小不一致
- [ ] 与其他页面的样式调整一致
- [ ] globe、china的图片title与图形距离过近

**Comment by zhuozihan** [comment]
工业控制分支
