### ISSUE TITLE
后台功能

### ISSUE THREAD

**Issue by zhuozihan** [zsxt/inspire#27]
- [ ] 当用admin的role登录时，默认进入后台页面
- [ ] 用户管理功能（router），列表显示所有用户详细信息（除了admin），选中支持删除、修改操作；加一个按键，支持新用户注册功能。

**Comment by pdliu** [comment]
这个superuser跟admin是什么关系? admin还能注册新用户吗?

**Comment by zhuozihan** [comment]
那就不用加superuser的role了，直接用admin吧
