### ISSUE TITLE
工控细节调整

### ISSUE THREAD

**Issue by zhuozihan** [zsxt/inspire#28]
- [x] 实时画面、漏洞渗透导航栏顺序调整一下，即实时画面在前
- [x] 监控预警的router去掉，暂时不显示
- [ ] 漏洞渗透的IP输入框内容可以选中
- [x] 点示start按钮，右侧状态栏显示“开始攻击”，点击stop状态栏，显示“停止攻击”
- [x] 实时画面，上部导航栏选中后颜色或样式变一下，直观突出选中的是哪一项
- [x] 系统介绍，原先有个title，加上

**Comment by iEverX** [comment]
输入框可以选中，这个已经在display分支修改了，不需要在这里改了
