### ISSUE TITLE
其他

### ISSUE THREAD

**Issue by iEverX** [zsxt/inspire#4]
- [x] 注释掉“拓扑展示”页面
- [x] 完成“注册用户”功能
- [x] 目前页面不支持选中操作，查找一下问题所在
- [x] 前端总是报这个错误：Failed to parse SourceMap: http://host/toastr.js.map

**Comment by iEverX** [comment]
不是不支持选中，是选中的颜色在css里改为了transparent，已修改

**Comment by zhuozihan** [comment]
前端总是报这个错误：Failed to parse SourceMap: http://host/toastr.js.map

**Comment by iEverX** [comment]
toastr这个错误，原因是在chrome开启使用sourcemap之后，chrome会请求sourcemp用于调试，而这个文件在工程中不存在。可以不用管

**Comment by zhuozihan** [comment]
develop分支
