### ISSUE TITLE
网络安全事件细节调整

### ISSUE THREAD

**Issue by zhuozihan** [zsxt/inspire#8]
- [x] 安全事件统计中间的柱状图，换成echart看看效果，现在屏幕分辨率一低，图就缩到上面去了，下边留了很大空白，很不好看
- [x] 或者是把源IP TOP5的表格缩短，把柱图长度扩大试试
- [x] 下面世界地图宽度，适当缩小，加长旁边2个饼图的宽度

**Comment by iEverX** [comment]
柱状图高度由100改为150

**Comment by zhuozihan** [comment]
柱状图高度改为150后，大分辨率就有问题了，能否根据分辨率适配？

**Comment by iEverX** [comment]
改的是display分支
